
package medicalassessment.abs.allianz.tr.medicalassessment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import medicalassessment.abs.allianz.tr.medicalassessment.datamodel.MedicalAssessmentRequest;
import medicalassessment.abs.allianz.tr.medicalassessment.datamodel.MedicalAssessmentResponse;
import medicalassessment.abs.allianz.tr.medicalassessment.datamodel.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "medicalAssessment", targetNamespace = "http://tr.allianz.abs.medicalAssessment/medicalAssessment/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MedicalAssessment {


    /**
     * 
     * @param parameters
     * @return
     *     returns medicalassessment.abs.allianz.tr.medicalassessment.datamodel.MedicalAssessmentResponse
     */
    @WebMethod(action = "http://tr.allianz.abs.medicalAssessment/medicalAssessment/getMedicalAssessmentStatus")
    @WebResult(name = "medicalAssessmentResponse", targetNamespace = "http://tr.allianz.abs.medicalAssessment/medicalAssessment/datamodel", partName = "parameters")
    public MedicalAssessmentResponse getMedicalAssessmentStatus(
        @WebParam(name = "medicalAssessmentRequest", targetNamespace = "http://tr.allianz.abs.medicalAssessment/medicalAssessment/datamodel", partName = "parameters")
        MedicalAssessmentRequest parameters);

}
